"""Browser end-to-end check of flows A–E against the built app (vite preview on :4173)."""
import re, sys, os
from playwright.sync_api import sync_playwright, expect

BASE = __import__("os").environ.get("BASE", "http://localhost:4173/")
OUT = os.environ.get("SHOTS", "shots")
os.makedirs(OUT, exist_ok=True)
errors = []
step_no = [0]

def shot(page, name):
    step_no[0] += 1
    page.screenshot(path=f"{OUT}/{step_no[0]:02d}-{name}.png", full_page=False)

def log(msg):
    print("  ✓", msg, flush=True)

def fill_code(page):
    # Use the on-screen prototype code.
    page.get_by_role("button", name="Fill in").first.click()

with sync_playwright() as p:
    browser = p.chromium.launch(executable_path="/opt/pw-browsers/chromium-1194/chrome-linux/chrome")
    ctx = browser.new_context(viewport={"width": 1360, "height": 900})
    pt = ctx.new_page()
    for pg in [pt]:
        pg.on("console", lambda m: errors.append(f"console {m.type}: {m.text}") if m.type == "error" else None)
        pg.on("pageerror", lambda e: errors.append(f"pageerror: {e}"))
    pt.set_default_timeout(8000)

    print("Flow A — sign up, onboarding, add a record")
    pt.goto(BASE)
    expect(pt.get_by_role("heading", name=re.compile("Your health"))).to_be_visible()
    shot(pt, "landing")
    pt.get_by_role("link", name="Get started").first.click()
    pt.get_by_label("Full name").fill("Kiran Rao")
    pt.get_by_label("Date of birth").fill("1992-05-17")
    pt.get_by_label("Email").fill("kiran.rao@example.com")
    pt.get_by_label("Mobile number").fill("+91 90909 12345")
    pt.get_by_label(re.compile(r"^Password")).fill("Health2026")
    pt.get_by_label("Confirm password").fill("Health2026")
    pt.get_by_role("button", name="Continue").click()
    expect(pt.get_by_text("Please accept to continue")).to_be_visible()
    pt.locator("label.check input").check()
    pt.get_by_role("button", name="Continue").click()
    expect(pt.get_by_role("heading", name="Enter your code")).to_be_visible()
    shot(pt, "otp")
    fill_code(pt)
    expect(pt.get_by_role("heading", name=re.compile("Welcome, Kiran"))).to_be_visible()
    log("sign-up with OTP")
    expect(pt.get_by_role("button", name="Skip for now")).to_have_count(0)
    pt.get_by_role("button", name="Continue").click()
    expect(pt.get_by_text("Choose your blood group")).to_be_visible()
    pt.get_by_label("Blood group").select_option("O+")
    shot(pt, "onboarding")
    pt.get_by_role("button", name="Continue").click()
    pt.get_by_role("button", name="Continue").click()
    expect(pt.get_by_text(re.compile("Add an emergency contact"))).to_be_visible()
    log("blood group and emergency contact are required")
    pt.get_by_label("Name").fill("Asha Rao")
    pt.get_by_label("Relationship").fill("Mother")
    pt.get_by_label("Phone").fill("+91 90909 00000")
    pt.get_by_role("button", name="Continue").click()
    pt.get_by_role("button", name="Continue").click()
    expect(pt.get_by_text(re.compile("Add your allergies, or confirm"))).to_be_visible()
    pt.get_by_role("button", name="Add an allergy").click()
    pt.get_by_label("Allergen").fill("Sulfa drugs")
    pt.get_by_label("Severity").select_option("Severe")
    pt.get_by_label("Reaction").fill("Rash and swelling")
    pt.get_by_role("button", name="Continue").click()
    pt.get_by_label("I have no ongoing conditions").check()
    pt.get_by_role("button", name="Continue").click()
    pt.get_by_role("button", name="Add a medicine").click()
    pt.get_by_label(re.compile(r"^Medicine")).fill("Vitamin D3")
    pt.get_by_label(re.compile(r"^Dose")).fill("1000 IU")
    pt.get_by_label(re.compile(r"^How often")).select_option("Twice daily")
    expect(pt.get_by_label("Reminder 2", exact=True)).to_have_value("20:00")
    shot(pt, "onboarding-medicines")
    pt.get_by_role("button", name="Continue").click()
    pt.get_by_label(re.compile("never had surgery")).check()
    pt.get_by_role("button", name="Finish setup").click()
    expect(pt.get_by_role("heading", name="Kiran Rao")).to_be_visible()
    expect(pt.get_by_text("Sulfa drugs").first).to_be_visible()
    expect(pt.get_by_text("Vitamin D3").first).to_be_visible()
    log("onboarding → dashboard with allergy and today's medicine doses")
    shot(pt, "dashboard-new")
    pt.get_by_role("button", name="Add medical record").click()
    pt.get_by_role("listitem").filter(has_text="Vaccination").click()
    pt.get_by_label("Vaccine").fill("Tetanus (Td)")
    pt.get_by_label("Date given").fill("2025-11-03")
    pt.get_by_label("Dose", exact=True).fill("Booster")
    shot(pt, "add-record")
    pt.get_by_role("button", name="Save to my record").click()
    expect(pt).to_have_url(re.compile("#/app/timeline"))
    expect(pt.get_by_role("dialog", name="Record details")).to_be_visible()
    pt.get_by_role("button", name="Close panel").click()
    expect(pt.locator(".tl-list").get_by_text("Tetanus (Td)")).to_be_visible()
    log("record appears in timeline")
    pt.goto(BASE + "#/app/records?category=vaccinations")
    expect(pt.locator(".rec-card").filter(has_text="Tetanus (Td)")).to_be_visible()
    log("record appears in Vaccinations category")
    patient_id = pt.evaluate("() => JSON.parse(localStorage.getItem('niveda.db')).patients.find(p => p.fullName === 'Kiran Rao').patientCode")

    print("Flow B — grant a doctor access")
    pt.goto(BASE + "#/app/access")
    pt.get_by_role("button", name="Grant access").first.click()
    pt.get_by_role("button", name=re.compile("Enter access code")).click()
    pt.get_by_label("Doctor access code").fill("PS-4821")
    pt.get_by_role("button", name="Find", exact=True).click()
    pt.get_by_role("button", name="This is my doctor").click()
    shot(pt, "grant-permissions")
    pt.get_by_role("button", name="Continue").click()
    pt.get_by_role("button", name="24 hours").click()
    pt.get_by_role("button", name="Continue").click()
    shot(pt, "grant-review")
    pt.get_by_role("button", name="Verify and grant").click()
    fill_code(pt)
    expect(pt.get_by_text("Dr. Priya Sharma can now see your record")).to_be_visible()
    pt.get_by_role("button", name="Done").click()
    expect(pt.locator(".access-card").filter(has_text="Dr. Priya Sharma")).to_be_visible()
    log("access granted with permissions, duration and OTP")
    shot(pt, "access-active")

    print("Flow C — doctor adds to the existing record")
    dr = ctx.new_page()
    dr.on("pageerror", lambda e: errors.append(f"doctor pageerror: {e}"))
    dr.on("console", lambda m: errors.append(f"doctor console: {m.text}") if m.type == "error" else None)
    dr.set_default_timeout(8000)
    dr.goto(BASE + "#/login")
    dr.get_by_role("button", name=re.compile("Continue as Dr. Priya")).click()
    fill_code(dr)
    expect(dr.get_by_role("heading", name="Dr. Priya Sharma")).to_be_visible()
    shot(dr, "doctor-dashboard")
    dr.locator(".list-item").filter(has_text="Kiran Rao").click()
    expect(dr.get_by_role("heading", name="Kiran Rao")).to_be_visible()
    expect(dr.get_by_role("alert").filter(has_text="SULFA DRUGS")).to_be_visible()
    log("doctor opens authorised patient with allergy alert")
    shot(dr, "doctor-patient")
    dr.get_by_role("button", name="Add to medical record").click()
    dr.get_by_label("Reason for visit").fill("Cough and fever for 4 days")
    dr.get_by_label("Symptoms").fill("Productive cough, fever 38.4°C, mild breathlessness")
    dr.get_by_label("Examination & notes").fill("Crackles right base. SpO2 97%.")
    dr.get_by_label("Condition").fill("Community-acquired pneumonia")
    dr.get_by_label("Severity").select_option("Mild")
    dr.get_by_role("button", name="Add medicine").click()
    dr.get_by_label(re.compile(r"^Medicine")).fill("Azithromycin")
    dr.get_by_label(re.compile(r"^Dose")).fill("500 mg")
    dr.get_by_label("Frequency").select_option("Once daily")
    dr.get_by_label("Days").fill("5")
    dr.get_by_role("button", name="Order a test").click()
    dr.get_by_label(re.compile(r"^Test")).fill("Chest X-ray")
    dr.get_by_label("Laboratory").fill("Clearview Imaging Centre")
    dr.locator("input[type=file]").first.set_input_files({"name": "chest-exam.pdf", "mimeType": "application/pdf", "buffer": b"%PDF-1.4\n%test\n"})
    expect(dr.get_by_text("chest-exam.pdf")).to_be_visible()
    shot(dr, "doctor-add-entry")
    dr.get_by_role("button", name="Save to patient medical record").click()
    dr.get_by_role("button", name="Save to record").click()
    expect(dr.get_by_role("heading", name=re.compile("Added to Kiran Rao"))).to_be_visible()
    shot(dr, "doctor-saved")
    log("consultation + diagnosis + prescription + lab order + attachment saved")

    pt.goto(BASE + "#/app/timeline")
    card = pt.locator(".rec-card").filter(has_text="Cough and fever for 4 days")
    expect(card).to_be_visible()
    expect(card.get_by_text("Dr. Priya Sharma")).to_be_visible()
    expect(card.get_by_text("Azithromycin")).to_be_visible()
    expect(pt.locator(".tl-list").get_by_text("Tetanus (Td)")).to_be_visible()
    log("entry appears in the patient's existing timeline, attributed")
    shot(pt, "patient-timeline-after")
    card.get_by_role("button", name=re.compile("Cough and fever")).click()
    expect(pt.get_by_text("Added by Dr. Priya Sharma")).to_be_visible()
    expect(pt.get_by_role("button", name="chest-exam.pdf")).to_be_visible()
    shot(pt, "record-drawer")
    pt.get_by_role("button", name="Close panel").click()
    pt.goto(BASE + "#/app/medications")
    expect(pt.get_by_role("button", name="Azithromycin", exact=True)).to_be_visible()
    expect(pt.get_by_role("region", name="Today’s doses")).to_be_visible()
    shot(pt, "medications-reminders")
    log("medication list updated with reminders")
    pt.goto(BASE + "#/app/notifications")
    expect(pt.get_by_text(re.compile("Dr. Priya Sharma added a consultation"))).to_be_visible()
    log("patient notified")

    print("Flow C2 — amendment keeps history")
    dr.goto(BASE + f"#/doctor/patients/{pt.evaluate('''() => JSON.parse(localStorage.getItem('niveda.db')).patients.find(p => p.fullName === 'Kiran Rao').id''')}")
    dr.get_by_role("tab", name="Timeline").click()
    dr.locator(".sub-row").filter(has_text="Community-acquired pneumonia").click()
    dr.get_by_role("button", name="Correct this entry").click()
    dr.get_by_label("Condition").fill("Right lower lobe pneumonia")
    dr.get_by_label("Reason for correction").fill("X-ray localised consolidation")
    dr.get_by_role("button", name="Review correction").click()
    dr.get_by_role("button", name="Save correction").click()
    expect(dr.get_by_text(re.compile("Corrected by Dr. Priya Sharma"))).to_be_visible()
    expect(dr.locator(".diff del").filter(has_text="Community-acquired pneumonia")).to_be_visible()
    shot(dr, "amendment")
    log("amendment shows original and new version")
    dr.get_by_role("button", name="Close panel").click()

    print("Flow D — revoke")
    pt.goto(BASE + "#/app/access")
    pt.locator(".access-card").filter(has_text="Dr. Priya Sharma").get_by_role("button", name="Revoke").click()
    pt.get_by_role("button", name="Revoke access").click()
    expect(pt.get_by_text("Access revoked")).to_be_visible()
    dr.reload()
    expect(dr.get_by_role("heading", name="You don’t have access to this record")).to_be_visible()
    expect(dr.get_by_text("Right lower lobe pneumonia")).to_have_count(0)
    shot(dr, "doctor-revoked")
    log("doctor loses access immediately")

    print("Flow E — audit trail")
    pt.goto(BASE + "#/app/activity")
    for text in ["Granted access", "Viewed medical history", "Added to the record", "Corrected an entry", "Revoked access"]:
        expect(pt.locator(".audit-item").filter(has_text=text).first).to_be_visible()
    shot(pt, "access-log")
    log("access log shows grant, views, additions, correction, revoke")

    print("Demo patient + mobile")
    pt.evaluate("() => sessionStorage.clear()")
    pt.goto(BASE + "#/login")
    pt.get_by_role("button", name=re.compile("Continue as Meera")).click()
    fill_code(pt)
    expect(pt.get_by_role("heading", name="Meera Iyer")).to_be_visible()
    shot(pt, "meera-dashboard")
    pt.goto(BASE + "#/app/timeline")
    expect(pt.get_by_role("heading", name="2018")).to_be_visible()
    shot(pt, "meera-timeline")
    pt.goto(BASE + "#/app/access?tab=requests")
    expect(pt.get_by_text("Dr. Arvind Rao")).to_be_visible()
    shot(pt, "meera-requests")
    pt.goto(BASE + "#/app/emergency")
    expect(pt.get_by_text("EMERGENCY MEDICAL INFORMATION")).to_be_visible()
    shot(pt, "meera-emergency")
    pt.keyboard.press("Control+k")
    pt.get_by_role("combobox", name="Search").fill("asthma")
    expect(pt.locator(".palette-item").first).to_be_visible()
    shot(pt, "search")
    pt.keyboard.press("Enter")
    expect(pt.get_by_role("dialog", name="Record details")).to_be_visible()
    log("global search opens the record")

    mob = browser.new_context(viewport={"width": 390, "height": 844}, is_mobile=True, has_touch=True)
    m = mob.new_page()
    m.on("pageerror", lambda e: errors.append(f"mobile pageerror: {e}"))
    m.goto(BASE + "#/login")
    m.get_by_role("button", name=re.compile("Continue as Meera")).click()
    fill_code(m)
    expect(m.get_by_role("heading", name="Meera Iyer")).to_be_visible()
    shot(m, "mobile-dashboard")
    m.goto(BASE + "#/app/timeline")
    m.wait_for_timeout(600)
    shot(m, "mobile-timeline")
    m.get_by_role("button", name="More").click()
    shot(m, "mobile-more")
    overflow = m.evaluate("() => document.documentElement.scrollWidth > window.innerWidth + 1")
    if overflow: errors.append("mobile: horizontal overflow on timeline")
    log("mobile layout renders with bottom navigation")

    browser.close()

real = [e for e in errors if "favicon" not in e and "ERR_TUNNEL" not in e]  # font CDN is blocked in the test sandbox
if real:
    print("\nERRORS:"); [print("  ", e) for e in real]; sys.exit(1)
print("\nAll browser flows passed")
